services:
  - type: web
    name: tripmakur
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn app:app"
    envVars:
      - key: API_KEY
        sync: false
    autoDeploy: true
    healthCheckPath: "/"

