services:
  - type: web
    name: tripmakur
    env: python
    plan: starter
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn app:app"
    envVars:
      - key: FLASK_SECRET_KEY
      - key: FLIGHTAPI_KEY
      - key: AMADEUS_CLIENT_ID
      - key: AMADEUS_CLIENT_SECRET
      - key: DEFAULT_TZ
        value: America/Chicago


